# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hookey', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Student', verbose_name='\u041f\u0440\u043e\u0433\u0443\u043b\u044f\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u0416\u0443\u0440\u043d\u0430\u043b',
                'verbose_name_plural': '\u0416\u0443\u0440\u043d\u0430\u043b\u0438',
            },
        ),
    ]
